require(GeneFamilies)
options(mc.cores = getMcCores())
library(dotenv)

library(dplyr)
library(tidyr)
library(tibble)

output_data_dir <- Sys.getenv("OUTPUT_DATA_DIR")

message("USAGE: Rscript exec/load_genefamilies_data.R <families_file> <counts_file>")

message("input.args[[1]]: <families_file>, generated by Orthofinder")
message("<families_file> containing gene-family clusters and the respective gene members")

message("input.args[[2]]: <counts_file>")
message("<counts_file> containing ... ")

input.args <- commandArgs(trailingOnly = TRUE)

input.args[[1]] <- "experiments/test/Orthogroups.tsv"


families.df <-  read.table(input.args[[1]], 
                header = TRUE, sep = "\t", 
                comment.char = "", quote = "", na.strings = "", 
                colClasses = rep("character", ncol(read.table(input.args[[1]], header = TRUE, sep = "\t"))))

# Automatically define the vector of gene columns by excluding 'Family'
gene_columns <- setdiff(names(families.df), "Family")

# Group by Family and create nested lists for each family
families.lst <- families.df %>%
                group_by(Family) %>%
                summarise(across(all_of(gene_columns), ~ list(.))) %>%
                nest(data = all_of(gene_columns)) %>%
                mutate(cluster_name = paste("Orthogroup_", row_number(), sep = "")) %>%
                select(cluster_name, data) %>%
                deframe()


# Save data:
save(families.lst, families.df, file = file.path(output_data_dir, "gene_families.RData"))

message("DONE")
