require(GeneFamilies)
options(mc.cores = getMcCores())

message("USAGE: Rscript path/2/GeneFamilies/exec/loadGeneFamilies.R path/2/GeneFamilies/data mcl_output.txt mcl_table.tsv")
message("EXPECTED INPUT FORMATS:")
message(" - mcl_output.txt is the textual output generated by the markob clustering tool mcl used on the all vs all sequence similarity search results. A single cluster (family) is expected per line and gene members to be separated by TAB.")
message(" - mcl_table a TAB separated table with the following header:\nid A.thaliana A.lyrata C.rubella C.hirsuta A.arabicum B.rapa E.salsugineum S.parvula")

readMclOutputTest <- function(path.2.mcl.out, family.name.prefix = "cluster_") {
    sys.cmd <- paste("awk 'NR==1 {cluster=\"", family.name.prefix, "\" NR; for (i = 1; i <= NF; i++) { print cluster \"\\t\" $i }} NR>1 {cluster=\"",
    family.name.prefix, "\" NR; for (i = 2; i <= NF; i++) { print cluster \"\\t\" $i }}' ",
        path.2.mcl.out, sep = "")
    fread(sys.cmd, stringsAsFactors = FALSE, sep = "\t",
        colClasses = rep("character", 2),
        col.names = c("Family", "Gene"), na.strings = "",
        data.table = FALSE)
}

input.args <- commandArgs(trailingOnly = TRUE)

families.genes.df <- readMclOutputTest(input.args[[2]])
# print(families.genes.df)
families.lst <- mclDataFrameAsList(families.genes.df)
# print(families.lst)
families.df <- read.table(input.args[[3]], sep = "\t", header = TRUE, stringsAsFactors = FALSE,
    comment.char = "", quote = "", na.strings = "", colClasses = c("character", rep("numeric",
        12)))
families.df$size <- apply(families.df[, 2:12], 1, sum)

#' Save parsed data:
save(families.genes.df, families.lst, families.df, file = file.path(input.args[[1]], 
    "families.RData"))

message("DONE")