require(GeneFamilies)
options(mc.cores = getMcCores())
library(dotenv)

library(dplyr)
library(tidyr)
library(tibble)

# Set up output directory, defined in the .env file 
output_data_dir <- Sys.getenv("OUTPUT_DATA_DIR")

# Display usage information
message("USAGE: Rscript exec/load_genefamilies_data.R <families_file>")

message("input.args[[1]]: <families_file>, generated by Orthofinder.")
message("<families_file> contains gene-family clusters and their respective gene members.")

# Parse input arguments
input.args <- commandArgs(trailingOnly = TRUE)


families.df <-  read.table(input.args[[1]], 
                header = TRUE, sep = "\t", 
                comment.char = "", quote = "", na.strings = "", 
                colClasses = rep("character", ncol(read.table(input.args[[1]], header = TRUE, sep = "\t"))))

# Automatically define the vector of gene columns by excluding the 'Family' column
gene_columns <- setdiff(names(families.df), "Family")

# Count the number of genes in each gene-family
families.counts.df <- families.df %>%
                mutate(across(all_of(gene_columns), 
                ~lengths(strsplit(., ",\\s*"))))

# Add size column as sum of counts per row
families.counts.df <- families.counts.df %>% rowwise() %>%
               mutate(size = sum(c_across(all_of(gene_columns)))) %>% ungroup()

# Group by Family and create nested lists for each family and species column
families.lst <- families.df %>%
                group_by(Family) %>%
                summarise(across(all_of(gene_columns), ~ list(.))) %>%
                nest(data = all_of(gene_columns)) %>%
                select(Family, data) %>% deframe()

# Save data:
save(families.lst, families.df, families.counts.df,
     file = file.path(output_data_dir, "gene_families.RData"))

message("DONE")
