require(GeneFamilies)
options(mc.cores = getMcCores())
library(parallel)

library(dotenv)
# Define directories for output data and results using environment variables
output_data_dir <- Sys.getenv("OUTPUT_DATA_DIR")
results_dir <- Sys.getenv("RESULTS_DIR")

# Librarys for handling Dataframes, Lists etc. more efficiently
library(dplyr)
library(tidyr)
library(purrr)
library(tibble)

# Display usage information
message("USAGE: Rscript exec/load_genefamilies_data.R <families_file>")

message("input.args[[1]]: <families_file>, generated by Orthofinder.")
message("<families_file> contains gene-family clusters and their respective gene members.")

message("important Note: stick to the naming convention of the Headers, else the script will not process the data correctly.")

# Parse input arguments
input.args <- commandArgs(trailingOnly = TRUE)

# Read the data
families.df <- read.table(input.args[[1]],
                header = TRUE, 
                sep = "\t",
                comment.char = "", 
                quote = "", 
                na.strings = "",
                colClasses = rep("character", ncol(read.table(input.args[[1]], header = TRUE, sep = "\t"))))

# Rename first column to "Family" if it's not already named that
names(families.df)[1] <- "Family"

# Automatically define the vector of gene columns by excluding the 'Family' column
gene_columns <- setdiff(names(families.df), "Family")

# Count the number of genes in each gene-family
families.counts.df <- families.df %>%
                mutate(across(all_of(gene_columns), 
                ~lengths(strsplit(., ",\\s*"))))

# Add size column as sum of counts per row
families.counts.df <- families.counts.df %>% rowwise() %>%
               mutate(size = sum(c_across(all_of(gene_columns)))) %>% ungroup()

# Group by Family and create nested lists for each family and species column
families.lst <- families.df %>%
                group_by(Family) %>%
                summarise(across(all_of(gene_columns), ~ list(.))) %>%
                nest(data = all_of(gene_columns)) %>%
                select(Family, data) %>% deframe()

# Save data:
save(families.lst, families.df, families.counts.df,
     file = file.path(output_data_dir, "gene_families.RData"))

message("DONE")
View()