
# load Genfamilies data

input.args <- commandArgs(trailingOnly = TRUE)

input.args[[2]] <- "mcl_output.txt"
input.args[[3]] <- 

readMclOutputTest <- function(path.2.mcl.out, family.name.prefix = "cluster_") {
    sys.cmd <- paste("awk 'NR==1 {cluster=\"", family.name.prefix, "\" NR; for (i = 1; i <= NF; i++) { print cluster \"\\t\" $i }} NR>1 {cluster=\"", family.name.prefix, "\" NR; for (i = 2; i <= NF; i++) { print cluster \"\\t\" $i }}' ", path.2.mcl.out, sep = "")

    fread(sys.cmd, stringsAsFactors = FALSE, sep = "\t",
        colClasses = rep("character", 2),
        col.names = c("Family", "Gene"), na.strings = "",
        data.table = FALSE)
}

families.genes.df <- readMclOutputTest(input.args[[2]])

families.lst <- mclDataFrameAsList(families.genes.df)

families.df <- read.table(input.args[[3]], sep = "\t", header = TRUE, stringsAsFactors = FALSE,
    comment.char = "", quote = "", na.strings = "", colClasses = c("character", rep("numeric",12)))

families.df$size <- apply(families.df[, 2:12], 1, sum)


save(families.genes.df, families.lst, families.df, file = file.path("families.RData"))












# mcl_output.txt is the textual output generated by the markob clustering tool mcl used on the all vs all sequence similarity search 
# results. A single cluster (family) is expected per line and gene members to be separated by TAB.

# mcl_output.txt -> A single cluster (family) is expected per line and gene members to be separated by TAB.
# mcl_table a TAB separated table with the following header:\nid A.thaliana A.lyrata C.rubella C.hirsuta A.arabicum B.rapa E.salsugineum S.parvula"


"x/data/mcl/mcl_output_modify.txt"

"x/data/mcl/mcl_output_counts_modify.tsv"

# function: family_funks.R, expression_funks
source("x/Section-2/family_funks.R") 
source("x/Section-2/family_funks.R") 


# Parameter richtig definieren !!! 12 Family-Members

# families.df$size <- apply(families.df[, 2:9], 1, sum)
# colClasses = c("character", rep("numeric", 8)


path.2.mcl.out <- "x/data/mcl/mcl_output_modify.txt"

readMclOutput <- function(path.2.mcl.out, family.name.prefix = "cluster_") {

    # Define a temporary file to store the output of the awk command
    temp_output_file <- tempfile()
    
    # Construct the awk command to process the MCL output
    sys.cmd <- paste("awk '{split($0,a,\"\\t\"); for (i in a) { print \"", 
                     family.name.prefix, "\" NR \"\\t\" a[i] }}' ", 
                     path.2.mcl.out, " > ", temp_output_file, sep = "")
    
    # Execute the command using the appropriate function based on the OS
    if (.Platform$OS.type == "unix") {
        system(sys.cmd)
    } else {
        shell(sys.cmd)
    }
    
    # Read the processed output from the temporary file
    families.genes.df <- fread(temp_output_file, stringsAsFactors = FALSE, sep = "\t", 
                               colClasses = rep("character", 2), 
                               col.names = c("Family", "Gene"), 
                               na.strings = "", data.table = FALSE)
    
    unlink(temp_output_file)
    
    return(families.genes.df)
}







families.genes.df <- readMclOutput("x/data/mcl/mcl_output_modify.txt")
families.lst <- mclDataFrameAsList(families.genes.df)

# Read the mcl_table.tsv file, quasi laden der tsv Datei 
families.df <- read.table("x/data/mcl/mcl_output_counts_modify.tsv", 
                          sep = "\t", 
                          header = TRUE, 
                          stringsAsFactors = FALSE, 
                          comment.char = "", 
                          quote = "", 
                          na.strings = "", 
                          colClasses = c("character", rep("numeric", 1)))


families.df$size <- apply(families.df[, 2:9], 1, sum)

#' Save parsed data:
save(families.genes.df, families.lst, families.df, file = file.path("families.RData"))

